Q-2: Usage of attributes of array such as ndim, shape, size, and method such as sum(), mean(), sort(), sqrt() etc...

In [1]:
import numpy as np

arr = np.array ([
        [1, 2, 3],
        [4, 5, 6]
    ])

print (arr)

arr_dimension = arr.ndim    
# it'll return the dimension of the array
print (f"It is a: {arr_dimension}D array\n")

arr_shape = arr.shape   
# it'll return the number of (rows) & (column) in the array
print (f"The no. of rows and columns in the array are: {arr_shape} respectively\n")

rows, cols = arr.shape
print (f"The no. of rows: {rows} & the no. of columns is: {cols}\n")


arr_size = arr.size
# it returns the total no of elements in the array
print (f"The total no. of elements in the array are: {arr_size}\n")

print (arr.dtype)
# Data type of the array
print()

print (arr.itemsize)
# byte of each element
print()

print (arr.nbytes)
# 1 element = 8 bytes 
# => 6 element = 8 x 6 = 48

[[1 2 3]
 [4 5 6]]
It is a: 2D array

The no. of rows and columns in the array are: (2, 3) respectively

The no. of rows: 2 & the no. of columns is: 3

The total no. of elements in the array are: 6

int64

8

48


In [ ]:
arr2 = np.array([
    [2, 4, 6],
    [8, 10, 2]
])   

arr_sum = arr2.sum()
print (arr_sum)

arr_mean = arr2.mean()
print (arr_mean)


arr_sqrt = np.sqrt(arr2)
print (arr_sqrt)


arr2_sort = np.sort (arr2)
# sort the elements according to the row and column of the array (means sort the elements of 1st array, 2nd....) & (same with the column)
print (arr2_sort)

32
5.333333333333333
[[1.41421356 2.         2.44948974]
 [2.82842712 3.16227766 1.41421356]]
[[ 2  4  6]
 [ 2  8 10]]
