### Q-4: Consider a list datatype (7d) then reshape it into 2D, 3D, matrix using numpy

In [1]:
import numpy as np

list = [1, 2, 3, 4, 5, 6, 7, 8]
print (f"{list}\n")

arr = np.array (list)   # converting list to array
print (f"{arr}\n")

arr_2d = arr.reshape (4, 2)     # 2x4 array (2 = row & 4 = array)
print (f"{arr_2d}\n")

another_2d = arr.reshape (2, 4) # 4x2 array (4 = row & 2 = column)
print (f"{another_2d}\n")

arr_3d = arr.reshape (2, 2, 2)  # 2 blocks × 2 rows × 2 columns
# 2x2x2 array
# (2 = row & 2 = column) inOneArray
# (2 = row & 2 = column) inAnotherArray
print (f"{arr_3d}\n")

[1, 2, 3, 4, 5, 6, 7, 8]

[1 2 3 4 5 6 7 8]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

